# Generated by Django 4.1.4 on 2022-12-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_hist_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hist',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
